spring.application.name=platform-backend

# Connection Pooler de Supabase (puerto 6543)
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.fuqpwqihmylaszmrsaeq
spring.datasource.password=elearning-backend
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

# Connection Pool (HikariCP)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
server.servlet.context-path=/api/v1

application.jwt.secret-key=supersecretkeythatshouldbelongandcomplexsupersecretkeythatshouldbelongandcomplex
application.jwt.token-prefix=Bearer 
application.jwt.token-expiration-after-days=7
application.jwt.refresh-token-expiration-after-days=30

# Supabase Storage
supabase.url=https://fuqpwqihmylaszmrsaeq.supabase.co
supabase.service-role-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1cXB3cWlobXlsYXN6bXJzYWVxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NjczMzE0NywiZXhwIjoyMDkyMzA5MTQ3fQ.5Rt0HdjCAjGtt6mrNLTN9N39iPs29qLsn8L34D72ElY
supabase.storage.bucket=contenidos

# Upload limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
